-- Schooly isolated schema objects. This file documents the live setup in the shared Supabase project.
-- Safar Link and unrelated projects use their existing tables and are not modified by Schooly.
create schema if not exists schooly_private;

create table if not exists public.schooly_settings(id boolean primary key default true check(id),school_name text not null default 'Schooly',logo_url text,favicon_url text,timezone text not null default 'Africa/Mogadishu',academic_year text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.schooly_profiles(id uuid primary key references auth.users(id) on delete cascade,account_id text not null unique,full_name text not null default '',role text not null check(role in ('admin','teacher','student')),active boolean not null default true,class_id uuid,phone text,photo_url text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.schooly_classes(id uuid primary key default gen_random_uuid(),name text not null unique,section text,academic_year text,class_teacher_id uuid references public.schooly_profiles(id) on delete set null,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.schooly_profiles add constraint schooly_profiles_class_id_fkey foreign key(class_id) references public.schooly_classes(id) on delete set null;
create table if not exists public.schooly_students(id uuid primary key default gen_random_uuid(),profile_id uuid not null unique references public.schooly_profiles(id) on delete cascade,admission_no text not null unique,gender text,date_of_birth date,guardian_name text,guardian_phone text,address text,fee_status text not null default 'pending' check(fee_status in ('paid','pending','partial')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.schooly_teachers(id uuid primary key default gen_random_uuid(),profile_id uuid not null unique references public.schooly_profiles(id) on delete cascade,employee_no text unique,subject text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.schooly_attendance(id uuid primary key default gen_random_uuid(),student_id uuid not null references public.schooly_students(id) on delete cascade,class_id uuid not null references public.schooly_classes(id) on delete cascade,attendance_date date not null,status text not null check(status in ('present','absent','late','excused')),marked_by uuid not null references public.schooly_profiles(id) on delete restrict,note text,created_at timestamptz not null default now(),unique(student_id,attendance_date));
create table if not exists public.schooly_fees(id uuid primary key default gen_random_uuid(),student_id uuid not null references public.schooly_students(id) on delete cascade,amount numeric(12,2) not null check(amount>=0),paid_amount numeric(12,2) not null default 0 check(paid_amount>=0 and paid_amount<=amount),due_date date,status text not null default 'pending' check(status in ('paid','pending','partial')),note text,recorded_by uuid references public.schooly_profiles(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.schooly_announcements(id uuid primary key default gen_random_uuid(),title text not null,body text not null,audience text not null default 'all' check(audience in ('all','teachers','students')),published boolean not null default true,created_by uuid not null references public.schooly_profiles(id) on delete restrict,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.schooly_audit_logs(id bigint generated always as identity primary key,actor_id uuid references auth.users(id) on delete set null,action text not null,entity_type text,entity_id uuid,before_data jsonb,after_data jsonb,created_at timestamptz not null default now());
create table if not exists public.schooly_bootstrap_control(id boolean primary key default true check(id),initialized boolean not null default false,initialized_at timestamptz,initialized_by uuid references auth.users(id) on delete set null);
